[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.120.0"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_VERSION = "0.120.0"
  HUGO_ENV = "production"
